CREATE TABLE [EDDATA].[History]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [ProfileID] INT NOT NULL, 
    [Date] DATETIME NOT NULL, 
    [SystemID] INT NOT NULL,
	CONSTRAINT FK_History_Asset FOREIGN KEY (Id) REFERENCES [EDDATA].[Asset] (Id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_History_System FOREIGN KEY (SystemID) REFERENCES [EDDATA].[System] (Id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_History_Profile FOREIGN KEY (Id) REFERENCES [EDDATA].[Profile] (Id) ON DELETE CASCADE ON UPDATE CASCADE 
)
