//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public int Id { get; set; }
        public int ItemTypeID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> ParentID { get; set; }
    
        public virtual History History { get; set; }
        public virtual Journey Journey { get; set; }
        public virtual Logfile Logfile { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual System System { get; set; }
    }
}
