//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journey
    {
        public int Id { get; set; }
        public Nullable<int> ProfileID { get; set; }
        public string Name { get; set; }
        public Nullable<int> HistoryStartID { get; set; }
        public Nullable<int> HistoryEndID { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual History History { get; set; }
        public virtual History History1 { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
