//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logfile
    {
        public int Id { get; set; }
        public int ProfileID { get; set; }
        public string LogfileName { get; set; }
        public System.DateTime LogFileDate { get; set; }
        public System.DateTime LastParsed { get; set; }
        public int LinesParsed { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
